import copy

from .activations import get_activations

# Tree prior weights per MITRA rationale (REGRESSION_SPEC.md Section 3.2)
# These weights reflect performance + diversity + distinctiveness
TREE_PRIOR_WEIGHTS = {
    'et': 0.15,   # Extra Trees: Distinctiveness booster (hard for SCM to mimic)
    'gb': 0.10,   # Gradient Boosting: Realistic boosting structure
    'dt': 0.05,   # Decision Tree: Axis-aligned discontinuities
    'rf': 0.08,   # Random Forest: Maximum diversity, weak standalone
    'dsrf': 0.02, # Directly Sampled RF: Optional overlap, keep small
}
# Note: SCM gets 0.60 weight, so tree priors total = 0.40


DEFAULT_FIXED_HP = {
    # SCMPrior
    "mix_probs": (0.7, 0.3),  # For backward compatibility (MLP, Tree)
    # Realism-oriented default mix for mix_scm:
    # [Linear, MLP, Conv, Tree, GP, TimeLagged]
    "mix_probas": [0.15, 0.18, 0.05, 0.44, 0.01, 0.17],
    # TreeSCM
    # Note: tree_model is now in DEFAULT_SAMPLED_HP to allow sampling different tree types
    "tree_depth_lambda": 0.5,
    "tree_n_estimators_lambda": 0.5,
    # Reg2Cls
    "balanced": False,
    "multiclass_ordered_prob": 0.0,
    "cat_prob": 0.2,
    "max_categories": float("inf"),
    "scale_by_max_features": False,
    "permute_features": True,
    "permute_labels": True,
    # Regression: Target Skewness
    "add_skewness": True,  # Default: enabled, can be overridden per stage
    # General realism defaults (kept conservative; sampled HP can override)
    "missingness_type": "mixed",
    "missingness_mix_probs": (0.55, 0.30, 0.15),  # MCAR, MAR, MNAR
    "missing_rate_feature_jitter": 0.20,
    "missing_max_feature_rate": 0.60,
    "missing_imputation_strategy": "mixed",
    "missing_imputation_mix_probs": (0.40, 0.25, 0.10, 0.20, 0.05),  # mean, median, constant, support_sample, gaussian
    "missing_constant_min": -0.5,
    "missing_constant_max": 0.5,
    "mar_logit_scale": 1.0,
    "mnar_logit_scale": 1.5,
    "randomize_column_ids": True,
    "return_metadata": False,
    "feature_type_categorical_max_unique": 24,
    "feature_type_categorical_max_frac": 0.12,
    "pareto_alpha_min": 1.8,
    "pareto_alpha_max": 3.5,
    "feature_student_t_df_min": 2.5,
    "feature_student_t_df_max": 6.0,
    "count_lambda_min": 1.0,
    "count_lambda_max": 15.0,
    "count_rate_temperature": 0.7,
    "count_nb_total_count": 6.0,
    "count_feature_log1p": True,
    "bounded_feature_min": 0.0,
    "bounded_feature_max": 1.0,
    "bounded_alpha_min": 0.7,
    "bounded_alpha_max": 3.0,
    "bounded_beta_min": 0.7,
    "bounded_beta_max": 3.0,
    "discretize_num_bins_min": 3,
    "discretize_num_bins_max": 12,
    # Prefer ordinal bins for discretization now that nominal categorical
    # columns are generated by a separate categorical-group pipeline.
    "discretize_by_ordinal": True,
    # Backward-compatible alias (older code may still read this key).
    "discretize_as_ordinals": True,
    "target_student_t_df_min": 2.0,
    "target_student_t_df_max": 5.0,
    "target_student_t_scale": 0.12,
    "target_mixture_std_low": 0.45,
    "target_mixture_std_high": 0.9,
    "bounded_target_scale": 2.0,
    "positive_lognormal_temperature": 1.0,
    "spurious_corr_strength": 1.2,
    "spurious_noise_scale": 0.30,
    "spurious_query_strength_scale": 0.5,
    "heteroscedastic_log_std_mean": -3.0,
    "heteroscedastic_log_std_std": 0.5,
    "heteroscedastic_dependency_strength": 0.5,
    "heteroscedastic_noise_scale": 1.0,
    "near_duplicate_noise_scale": 0.05,
    "linear_combination_noise_scale": 0.05,
    "gross_outlier_multiplier_min": 8.0,
    "gross_outlier_multiplier_max": 40.0,
    # Finance-style dynamics (enabled stochastically via finance_realism_rate).
    "finance_realism_rate": 0.0,
    "finance_input_tail_rate": 0.10,
    "finance_input_pareto_alpha": 1.8,
    "finance_input_shock_prob": 0.06,
    "finance_input_shock_scale": 0.8,
    "finance_input_negative_shock_prob": 0.35,
    "finance_garch_rate": 0.8,
    "finance_garch_omega": 0.001,
    "finance_garch_alpha": 0.12,
    "finance_garch_beta": 0.84,
    "finance_jump_rate": 0.6,
    "finance_jump_lambda": 0.015,
    "finance_jump_log_mu": 0.9,
    "finance_jump_log_sigma": 0.5,
    "finance_jump_crash_prob": 0.15,
    "use_kumaraswamy_warping": False,
    "kumaraswamy_a": 2.0,
    "kumaraswamy_b": 5.0,
    "heavy_tail_feature_distribution": "mixed",
    "count_feature_distribution": "mixed",
    "bounded_feature_distribution": "mixed",
    "discretize_feature_mode": "quantile",
    # Categorical attribute injection (disabled by default)
    "categorical_attr": False,
    "categorical_attr_num_cols_rate_min": 0.1,
    "categorical_attr_num_cols_rate_max": 0.4,
    "categorical_attr_num_groups": 6,
    "categorical_attr_effect": "none",
    "categorical_attr_effect_strength": 0.5,
    "categorical_attr_group_imbalance": 0.7,
    # Cross-sectional rank normalization (disabled by default)
    "apply_cross_sectional_rank": False,
    "cross_sectional_rank_feature_proportion": 0.1,
    # Censored targets (survival analysis, disabled by default)
    "apply_censored_targets": False,
    "censored_target_weibull_lambda": 1.0,
    "censored_target_weibull_k": 1.5,
    "censored_target_exp_eta": 0.5,
    "use_strictly_positive_target": False,
}

DEFAULT_SAMPLED_HP = {
    # Reg2Cls
    "multiclass_type": {"distribution": "meta_choice", "choice_values": ["value", "rank"]},
    # MLPSCM
    "mlp_activations": {
        "distribution": "meta_choice_mixed",
        "choice_values": get_activations(random=True, scale=True, diverse=True),
    },
    "block_wise_dropout": {"distribution": "meta_choice", "choice_values": [True, False]},
    "mlp_dropout_prob": {"distribution": "meta_beta", "scale": 0.9, "min": 0.1, "max": 5.0},
    # ConvSCM
    "conv_activations": {
        "distribution": "meta_choice_mixed",
        "choice_values": get_activations(random=True, scale=True, diverse=True),
    },
    "conv_dropout_prob": {"distribution": "meta_beta", "scale": 0.9, "min": 0.1, "max": 5.0},
    "hidden_channels": {
        "distribution": "meta_trunc_norm_log_scaled",
        "max_mean": 10,
        "min_mean": 3,
        "round": True,
        "lower_bound": 3,
    },
    "kernel_size": {"distribution": "meta_choice", "choice_values": [3, 5, 7]},
    "stride": {"distribution": "meta_choice", "choice_values": [1, 2]},
    "padding": {"distribution": "meta_choice", "choice_values": [0, 1, 2]},
    # MLPSCM and TreeSCM
    "is_causal": {"distribution": "meta_choice", "choice_values": [True, False]},
    "num_causes": {
        "distribution": "meta_trunc_norm_log_scaled",
        "max_mean": 12,
        "min_mean": 1,
        "round": True,
        "lower_bound": 1,
    },
    "y_is_effect": {"distribution": "meta_choice", "choice_values": [True, False]},
    "in_clique": {"distribution": "meta_choice", "choice_values": [True, False]},
    "sort_features": {"distribution": "meta_choice", "choice_values": [True, False]},
    "num_layers": {
        "distribution": "meta_trunc_norm_log_scaled",
        "max_mean": 3,
        "min_mean": 2.0,
        "round": True,
        "lower_bound": 2,
    },
    "hidden_dim": {
        "distribution": "meta_trunc_norm_log_scaled",
        "max_mean": 10,
        "min_mean": 3,
        "round": True,
        "lower_bound": 3,
    },
    "init_std": {
        "distribution": "meta_trunc_norm_log_scaled",
        "max_mean": 0.5,  # Reduced from 2.0 to 0.5 for better stability with Exp/Square activations
        "min_mean": 0.01,
        "round": False,
        "lower_bound": 0.0,
    },
    "noise_std": {
        "distribution": "meta_trunc_norm_log_scaled",
        "max_mean": 0.3,
        "min_mean": 0.0001,
        "round": False,
        "lower_bound": 0.0,
    },
    "sampling": {"distribution": "meta_choice", "choice_values": ["normal", "mixed", "uniform", "beta"]},
    "pre_sample_cause_stats": {"distribution": "meta_choice", "choice_values": [True, False]},
    "pre_sample_noise_std": {"distribution": "meta_choice", "choice_values": [True, False]},
    # GPSCM
    "length_scale": {
        "distribution": "meta_log_uniform",
        "min": 0.1,
        "max": 3.0,  # Reduced from 10.0 to prevent numerical instability with coords in [0,1]
    },
    "signal_variance": {
        "distribution": "meta_log_uniform",
        "min": 0.1,
        "max": 5.0,
    },
    "noise_variance": {
        "distribution": "meta_log_uniform",
        "min": 0.01,
        "max": 0.5,
    },
    "gp_combination": {
        "distribution": "meta_choice",
        "choice_values": ["linear", "quadratic", "mlp"],
    },
    # Finance-style realism sampling (only a subset of datasets will activate it).
    "finance_realism_rate": {
        "distribution": "meta_choice",
        "choice_values": [0.03, 0.045, 0.06],
    },
    "finance_input_tail_rate": {
        "distribution": "meta_choice",
        "choice_values": [0.0, 0.05, 0.10, 0.20],
    },
    "finance_input_pareto_alpha": {
        "distribution": "meta_choice",
        "choice_values": [1.3, 1.6, 1.9, 2.3],
    },
    "finance_input_shock_prob": {
        "distribution": "meta_choice",
        "choice_values": [0.02, 0.05, 0.08, 0.12],
    },
    "finance_input_shock_scale": {
        "distribution": "meta_choice",
        "choice_values": [0.4, 0.7, 1.0, 1.4],
    },
    "finance_garch_rate": {
        "distribution": "meta_choice",
        "choice_values": [0.0, 0.5, 0.8, 1.0],
    },
    "finance_garch_omega": {
        "distribution": "meta_log_uniform",
        "min": 1e-4,
        "max": 1e-2,
    },
    "finance_garch_alpha": {
        "distribution": "meta_choice",
        "choice_values": [0.05, 0.10, 0.15, 0.20],
    },
    "finance_garch_beta": {
        "distribution": "meta_choice",
        "choice_values": [0.70, 0.80, 0.88, 0.93],
    },
    "finance_jump_rate": {
        "distribution": "meta_choice",
        "choice_values": [0.0, 0.4, 0.7, 1.0],
    },
    "finance_jump_lambda": {
        "distribution": "meta_choice",
        "choice_values": [0.005, 0.01, 0.02, 0.04],
    },
    "finance_jump_log_mu": {
        "distribution": "meta_choice",
        "choice_values": [0.5, 0.8, 1.1],
    },
    "finance_jump_log_sigma": {
        "distribution": "meta_choice",
        "choice_values": [0.35, 0.50, 0.70],
    },
    "finance_jump_crash_prob": {
        "distribution": "meta_choice",
        "choice_values": [0.05, 0.15, 0.25],
    },
    # TimeLaggedSCM
    "time_lagged_lag_order": {
        "distribution": "meta_choice",
        "choice_values": [1, 2, 3, 4, 6, 8],
    },
    "time_lagged_weight_sparsity": {
        "distribution": "meta_choice",
        "choice_values": [0.40, 0.55, 0.70, 0.82, 0.90],
    },
    "time_lagged_output_noise_std": {
        "distribution": "meta_log_uniform",
        "min": 0.001,
        "max": 0.08,
    },
    # Random node selection strategy (disjoint X, y sampling from joint distribution)
    "use_joint_covariance_sampling": {
        "distribution": "meta_choice",
        "choice_values": [True, False]  # Mix of both strategies
    },
    # TreeSCM: Tree type selection
    # Weights per MITRA rationale: ET 0.15, GB 0.10, DT 0.08, RF 0.05, DSRF 0.02
    # (SCM gets 0.60, so tree priors total = 0.40)
    "tree_model": {
        "distribution": "meta_choice",
        "choice_values": ["extra_trees", "xgboost", "decision_tree", "random_forest", "dsrf"],
    },
    # Regression: Target Normalization Method
    "target_norm_method": {
        "distribution": "meta_choice",
        "choice_values": ["zscore", "minmax"],
    },
    # Feature realism: missingness, heavy tails, count, bounded, discretization
    "missing_rate": {
        "distribution": "meta_choice",
        "choice_values": [0.065, 0.07, 0.075],
    },
    "missingness_type": {
        "distribution": "meta_choice",
        "choice_values": ["mixed"],
    },
    "missingness_mcar_prob": {
        "distribution": "meta_choice",
        "choice_values": [0.45, 0.55, 0.65, 0.75],
    },
    "missingness_mar_prob": {
        "distribution": "meta_choice",
        "choice_values": [0.15, 0.25, 0.30, 0.40],
    },
    "missingness_mnar_prob": {
        "distribution": "meta_choice",
        "choice_values": [0.05, 0.10, 0.15, 0.20],
    },
    "missing_rate_feature_jitter": {
        "distribution": "meta_choice",
        "choice_values": [0.10, 0.20, 0.30, 0.40],
    },
    "mar_logit_scale": {
        "distribution": "meta_choice",
        "choice_values": [0.75, 1.0, 1.25, 1.5],
    },
    "mnar_logit_scale": {
        "distribution": "meta_choice",
        "choice_values": [1.0, 1.25, 1.5, 2.0],
    },
    "missing_imputation_strategy": {
        "distribution": "meta_choice",
        "choice_values": ["mixed", "mixed", "mean", "median", "support_sample", "gaussian", "constant"],
    },
    "heavy_tail_feature_rate": {
        "distribution": "meta_choice",
        "choice_values": [0.42, 0.46, 0.50],
    },
    "heavy_tail_feature_distribution": {
        "distribution": "meta_choice",
        "choice_values": ["student_t", "pareto", "mixed"],
    },
    "count_feature_rate": {
        "distribution": "meta_choice",
        "choice_values": [0.0, 0.0, 0.05, 0.10, 0.15, 0.25],
    },
    "count_feature_distribution": {
        "distribution": "meta_choice",
        "choice_values": ["poisson", "negative_binomial", "mixed"],
    },
    "bounded_feature_rate": {
        "distribution": "meta_choice",
        "choice_values": [0.0, 0.0, 0.05, 0.10, 0.15, 0.25],
    },
    "bounded_feature_distribution": {
        "distribution": "meta_choice",
        "choice_values": ["sigmoid", "beta", "mixed"],
    },
    "discretize_feature_rate": {
        "distribution": "meta_choice",
        "choice_values": [0.25, 0.30, 0.35],
    },
    "discretize_feature_mode": {
        "distribution": "meta_choice",
        "choice_values": ["uniform", "quantile"],
    },
    "use_kumaraswamy_warping": {
        "distribution": "meta_choice",
        "choice_values": [False, False, False, True],
    },
    "kumaraswamy_a": {
        "distribution": "meta_log_uniform",
        "min": 0.5,
        "max": 5.0,
    },
    "kumaraswamy_b": {
        "distribution": "meta_log_uniform",
        "min": 0.5,
        "max": 5.0,
    },
    # Target realism: heavy tails + multimodal mixture
    "heavy_tail_target_rate": {
        "distribution": "meta_choice",
        "choice_values": [0.0, 0.0, 0.10, 0.20, 0.35],
    },
    "multimodal_target_rate": {
        "distribution": "meta_choice",
        "choice_values": [0.0, 0.0, 0.10, 0.20, 0.30],
    },
    "bounded_target_rate": {
        "distribution": "meta_choice",
        "choice_values": [0.0, 0.0, 0.10, 0.20],
    },
    "positive_lognormal_target_rate": {
        "distribution": "meta_choice",
        "choice_values": [0.0, 0.0, 0.05, 0.10, 0.20],
    },
    "label_flip_rate": {
        "distribution": "meta_choice",
        "choice_values": [0.01, 0.02, 0.03],
    },
    "heteroscedastic_feature_rate": {
        "distribution": "meta_choice",
        "choice_values": [0.12, 0.15, 0.18],
    },
    "near_duplicate_feature_rate": {
        "distribution": "meta_choice",
        "choice_values": [0.0, 0.0, 0.05, 0.10, 0.15],
    },
    "linear_combination_feature_rate": {
        "distribution": "meta_choice",
        "choice_values": [0.0, 0.0, 0.05, 0.10, 0.15],
    },
    "rank_feature_rate": {
        "distribution": "meta_choice",
        "choice_values": [0.0, 0.0, 0.05, 0.10, 0.20],
    },
    "gross_outlier_cell_rate": {
        "distribution": "meta_choice",
        "choice_values": [0.0, 0.0, 0.0005, 0.001, 0.002, 0.005],
    },
    # Joint realism: confounding and spurious correlations
    "confounding_strength": {
        "distribution": "meta_choice",
        "choice_values": [0.35, 0.40, 0.45],
    },
    "spurious_feature_rate": {
        "distribution": "meta_choice",
        "choice_values": [0.06, 0.08, 0.10],
    },
    "spurious_query_flip_prob": {
        "distribution": "meta_choice",
        "choice_values": [0.0, 0.25, 0.50, 0.75],
    },
    # HybridSCM
    "max_parents": {
        "distribution": "meta_choice",
        "choice_values": [1, 2, 3, 4]
    },
    "num_roots": {
        "distribution": "meta_choice",
        "choice_values": [5, 10, 15]
    },
    # Categorical attribute injection
    # ~30 % of datasets get categorical attribute columns
    "categorical_attr": {
        "distribution": "meta_choice",
        "choice_values": [False, False, False, False, False, False, False, True, True, True],
    },
    # Rate of categorical columns relative to num_features (sampled uniformly in [rate_min, rate_max])
    "categorical_attr_num_cols_rate_min": {
        "distribution": "meta_choice",
        "choice_values": [0.05, 0.05, 0.10, 0.10, 0.15, 0.20, 0.25],
    },
    "categorical_attr_num_cols_rate_max": {
        "distribution": "meta_choice",
        "choice_values": [0.10, 0.15, 0.20, 0.25, 0.30, 0.35, 0.40],
    },
    # Mostly binary (gender-like), occasional multi-group (race / age / profession)
    "categorical_attr_num_groups": {
        "distribution": "meta_choice",
        "choice_values": [2, 2, 2, 2, 3, 3, 4, 5],
    },
    # Effect mechanism: intercept shift, slope shift, both, or none
    "categorical_attr_effect": {
        "distribution": "meta_choice",
        "choice_values": ["offset", "projection", "both", "none", "none"],
    },
    # Effect magnitude as a multiple of the support-set y std
    "categorical_attr_effect_strength": {
        "distribution": "meta_choice",
        "choice_values": [0.3, 0.5, 0.5, 0.75, 1.0, 1.5, 2.0],
    },
    # Class imbalance: 0 = uniform groups, higher = dominant-group skew
    "categorical_attr_group_imbalance": {
        "distribution": "meta_choice",
        "choice_values": [0.0, 0.0, 0.0, 0.2, 0.4, 0.6],
    },
    # Cross-sectional rank normalization (quant finance standard)
    "apply_cross_sectional_rank": {
        "distribution": "meta_choice",
        "choice_values": [False, False, False, False, False, True, True, True],
    },
    # Proportion of features to rank-normalize
    "cross_sectional_rank_feature_proportion": {
        "distribution": "meta_choice",
        "choice_values": [0.01, 0.05, 0.1, 0.15],
    },
    # Censored targets (survival analysis)
    "apply_censored_targets": {
        "distribution": "meta_choice",
        "choice_values": [False, False, False, False, False, False, True, True],
    },
    # Weibull scale parameter for event times
    "censored_target_weibull_lambda": {
        "distribution": "meta_choice",
        "choice_values": [0.5, 0.75, 1.0, 1.25, 1.5, 2.0],
    },
    # Weibull shape parameter for event times
    "censored_target_weibull_k": {
        "distribution": "meta_choice",
        "choice_values": [0.8, 1.0, 1.2, 1.5, 2.0, 2.5],
    },
    # Exponential rate parameter for censoring times
    "censored_target_exp_eta": {
        "distribution": "meta_choice",
        "choice_values": [0.2, 0.3, 0.4, 0.5, 0.6, 0.8, 1.0],
    },
    # Positive-support target post-normalization toggle (mainly for survival-like setups).
    "use_strictly_positive_target": {
        "distribution": "meta_choice",
        "choice_values": [False, False, True],
    },
}


# Realism difficulty presets for quick stage control.
# Finance dynamics are intentionally controlled separately (stage presets in
# generation config), so realism profiles focus on generic tabular realism.
REALISM_PROFILE_OVERRIDES = {
    "low": {
        "missing_rate": [0.0, 0.0, 0.005, 0.01, 0.02, 0.03, 0.05, 0.08, 0.12],
        "heavy_tail_feature_rate": [0.0, 0.0, 0.02, 0.05, 0.10, 0.15],
        "count_feature_rate": [0.0, 0.0, 0.02, 0.05, 0.10, 0.15],
        "bounded_feature_rate": [0.0, 0.0, 0.03, 0.05, 0.10, 0.15],
        "discretize_feature_rate": [0.0, 0.0, 0.01, 0.03, 0.05, 0.10],
        "use_kumaraswamy_warping": [False, False, False, False],
        "heavy_tail_target_rate": [0.0, 0.0, 0.05, 0.10, 0.20],
        "multimodal_target_rate": [0.0, 0.0, 0.05, 0.10, 0.20],
        "bounded_target_rate": [0.0, 0.0, 0.05, 0.10],
        "positive_lognormal_target_rate": [0.0, 0.0, 0.02, 0.05, 0.10],
        "label_flip_rate": [0.0, 0.0, 0.005, 0.01, 0.02, 0.05],
        "heteroscedastic_feature_rate": [0.0, 0.0, 0.02, 0.05, 0.10],
        "near_duplicate_feature_rate": [0.0, 0.0, 0.02, 0.05, 0.10],
        "linear_combination_feature_rate": [0.0, 0.0, 0.02, 0.05, 0.10],
        "rank_feature_rate": [0.0, 0.0, 0.02, 0.05, 0.10],
        "gross_outlier_cell_rate": [0.0, 0.0, 0.0001, 0.0002, 0.0005, 0.001],
        "confounding_strength": [0.0, 0.0, 0.10, 0.20, 0.35, 0.50],
        "spurious_feature_rate": [0.0, 0.0, 0.01, 0.03, 0.05, 0.10],
        "spurious_query_flip_prob": [0.0, 0.15, 0.30, 0.50],
        "categorical_attr": [False, False, False, False, False, False, True],
        "categorical_attr_num_cols_rate_min": [0.03, 0.05, 0.08],
        "categorical_attr_num_cols_rate_max": [0.08, 0.12, 0.18],
        "categorical_attr_num_groups": [2, 2, 2, 3],
        "categorical_attr_effect": ["none", "none", "offset", "projection"],
        "categorical_attr_effect_strength": [0.2, 0.3, 0.5, 0.8],
        "categorical_attr_group_imbalance": [0.0, 0.1, 0.2, 0.4],
        "apply_cross_sectional_rank": [False, False, False, False, True],
        "cross_sectional_rank_feature_proportion": [0.01, 0.03, 0.05, 0.08],
        "apply_censored_targets": [False, False, False, False, False, True],
        "censored_target_weibull_lambda": [0.8, 1.0, 1.2],
        "censored_target_weibull_k": [1.0, 1.2, 1.5],
        "censored_target_exp_eta": [0.3, 0.5, 0.7],
        "use_strictly_positive_target": [False, False, True],
    },
    "mild": {
        "categorical_attr": [False, False, False, True, True],
        "categorical_attr_num_cols_rate_min": [0.05, 0.10, 0.15],
        "categorical_attr_num_cols_rate_max": [0.15, 0.25, 0.35],
        "categorical_attr_num_groups": [2, 2, 3, 4],
        "categorical_attr_effect": ["offset", "projection", "both", "none"],
        "categorical_attr_effect_strength": [0.3, 0.5, 0.75, 1.0, 1.5],
        "categorical_attr_group_imbalance": [0.0, 0.2, 0.4, 0.6],
        "apply_cross_sectional_rank": [False, False, True, True],
        "cross_sectional_rank_feature_proportion": [0.03, 0.05, 0.10, 0.15],
        "apply_censored_targets": [False, False, False, True],
        "censored_target_weibull_lambda": [0.75, 1.0, 1.25, 1.5],
        "censored_target_weibull_k": [1.0, 1.2, 1.5, 2.0],
        "censored_target_exp_eta": [0.3, 0.5, 0.7, 1.0],
        "use_strictly_positive_target": [False, True, True],
    },
    "hard": {
        "missing_rate": [0.0, 0.01, 0.03, 0.05, 0.08, 0.12, 0.16, 0.22, 0.30],
        "heavy_tail_feature_rate": [0.0, 0.05, 0.10, 0.20, 0.30, 0.40],
        "count_feature_rate": [0.0, 0.05, 0.10, 0.20, 0.30, 0.40],
        "bounded_feature_rate": [0.0, 0.05, 0.10, 0.20, 0.30, 0.40],
        "discretize_feature_rate": [0.0, 0.03, 0.06, 0.10, 0.15, 0.20],
        "use_kumaraswamy_warping": [False, False, True, True],
        "heavy_tail_target_rate": [0.0, 0.10, 0.20, 0.35, 0.50],
        "multimodal_target_rate": [0.0, 0.10, 0.20, 0.35, 0.50],
        "bounded_target_rate": [0.0, 0.10, 0.20, 0.30],
        "positive_lognormal_target_rate": [0.0, 0.05, 0.10, 0.20, 0.30],
        "label_flip_rate": [0.0, 0.01, 0.03, 0.05, 0.08, 0.10],
        "heteroscedastic_feature_rate": [0.0, 0.05, 0.10, 0.20, 0.30],
        "near_duplicate_feature_rate": [0.0, 0.05, 0.10, 0.15, 0.20],
        "linear_combination_feature_rate": [0.0, 0.05, 0.10, 0.15, 0.20],
        "rank_feature_rate": [0.0, 0.05, 0.10, 0.20, 0.30],
        "gross_outlier_cell_rate": [0.0, 0.0005, 0.001, 0.002, 0.005, 0.01],
        "confounding_strength": [0.0, 0.15, 0.30, 0.50, 0.75, 1.0],
        "spurious_feature_rate": [0.0, 0.03, 0.05, 0.10, 0.15, 0.25],
        "spurious_query_flip_prob": [0.0, 0.25, 0.50, 0.90],
        "categorical_attr": [False, True, True, True, True],
        "categorical_attr_num_cols_rate_min": [0.10, 0.15, 0.20, 0.25],
        "categorical_attr_num_cols_rate_max": [0.25, 0.35, 0.45, 0.55],
        "categorical_attr_num_groups": [2, 3, 4, 5, 6],
        "categorical_attr_effect": ["offset", "projection", "both", "both", "none"],
        "categorical_attr_effect_strength": [0.75, 1.0, 1.5, 2.0, 3.0],
        "categorical_attr_group_imbalance": [0.2, 0.4, 0.6, 0.8],
        "apply_cross_sectional_rank": [False, True, True, True, True],
        "cross_sectional_rank_feature_proportion": [0.05, 0.10, 0.15, 0.25],
        "apply_censored_targets": [False, True, True, True],
        "censored_target_weibull_lambda": [0.5, 0.75, 1.0, 1.25],
        "censored_target_weibull_k": [0.8, 1.0, 1.5, 2.5],
        "censored_target_exp_eta": [0.2, 0.3, 0.5, 0.8],
        "use_strictly_positive_target": [True, True, True, False],
    },
}


def _validate_realism_profile(profile: str) -> str:
    """Normalize and validate realism profile name."""
    p = str(profile).strip().lower()
    if p not in REALISM_PROFILE_OVERRIDES:
        raise ValueError(
            f"Unknown realism profile '{profile}'. Expected one of {list(REALISM_PROFILE_OVERRIDES.keys())}"
        )
    return p


def _pad_list(values, target_len):
    """Pad a list by repeating its last element."""
    if not values:
        return [0.0] * target_len
    if len(values) >= target_len:
        return values[:target_len]
    return values + [values[-1]] * (target_len - len(values))


def get_sampled_hp_with_realism_profile(profile: str = "mild", base_sampled_hp=None):
    """Return sampled HP dictionary with a realism preset applied."""
    profile = _validate_realism_profile(profile)
    hp = copy.deepcopy(base_sampled_hp if base_sampled_hp is not None else DEFAULT_SAMPLED_HP)

    overrides = REALISM_PROFILE_OVERRIDES.get(profile, {})
    for key, choice_values in overrides.items():
        if key in hp and isinstance(hp[key], dict):
            hp[key] = {**hp[key], "choice_values": list(choice_values)}
        else:
            hp[key] = {"distribution": "meta_choice", "choice_values": list(choice_values)}
    return hp


def blend_sampled_hp_realism_profiles(
    start_profile: str,
    end_profile: str,
    alpha: float,
    base_sampled_hp=None,
):
    """Blend two realism presets and return sampled HP dict.

    Numeric choice_values are linearly interpolated.
    Non-numeric (e.g., booleans) switch from start to end at alpha >= 0.5.
    """
    alpha = float(min(max(alpha, 0.0), 1.0))
    start_hp = get_sampled_hp_with_realism_profile(start_profile, base_sampled_hp=base_sampled_hp)
    end_hp = get_sampled_hp_with_realism_profile(end_profile, base_sampled_hp=base_sampled_hp)

    blended = copy.deepcopy(start_hp)
    all_keys = set(start_hp.keys()) | set(end_hp.keys())
    for key in all_keys:
        start_cfg = start_hp.get(key)
        end_cfg = end_hp.get(key)
        if not isinstance(start_cfg, dict) or not isinstance(end_cfg, dict):
            blended[key] = end_cfg if alpha >= 0.5 else start_cfg
            continue

        s_vals = start_cfg.get("choice_values")
        e_vals = end_cfg.get("choice_values")
        if not isinstance(s_vals, list) or not isinstance(e_vals, list):
            blended[key] = copy.deepcopy(end_cfg if alpha >= 0.5 else start_cfg)
            continue

        max_len = max(len(s_vals), len(e_vals))
        s_pad = _pad_list(list(s_vals), max_len)
        e_pad = _pad_list(list(e_vals), max_len)

        is_numeric = all(
            isinstance(v, (int, float)) and not isinstance(v, bool)
            for v in s_pad + e_pad
        )
        if is_numeric:
            mixed_raw = [(1.0 - alpha) * float(s) + alpha * float(e) for s, e in zip(s_pad, e_pad)]
            is_all_int = all(isinstance(v, int) and not isinstance(v, bool) for v in s_pad + e_pad)
            mixed_vals = [int(round(v)) for v in mixed_raw] if is_all_int else mixed_raw
        else:
            mixed_vals = e_pad if alpha >= 0.5 else s_pad

        blended[key] = {**start_cfg, "choice_values": mixed_vals}

    return blended

